# code: language=ansible
---
- name: ApiSix Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: apisix-overrides-yml.j2
    dest: "{{ apisix_helm_overrides }}"
    mode: 'u=rw,g=r,o=r'
  register: apisix_helm_overrides_result

- name: Add ApiSix chart repo
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm_repository:
    name: apisix
    repo_url: "https://charts.apiseven.com"

- name: Deploy ApiSix helm chart
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm:
    name: apisix
    release_namespace: apisix
    chart_ref: apisix/apisix
    chart_version: "{{ apisix_helm_version }}"
    create_namespace: true
    update_repo_cache: apisix_helm_overrides_result.changed | default(true)
    wait: true
    values_files:
      - "{{ apisix_helm_overrides }}"
  when: (check_helm_deployment | default(true)) or (apisix_helm_overrides_result.changed | default(true))
