# code: language=ansible
---
- name: Cert Manager Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: cert-manager-overrides-yml.j2
    dest: "{{ cert_manager_helm_overrides }}"
    mode: 'u=rw,g=r,o=r'
  register: cert_manager_helm_overrides_result

- name: Add Cert Manager chart repo
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm_repository:
    name: cert-manager
    repo_url: "https://charts.jetstack.io"

- name: Deploy Cert Manager helm chart
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm:
    name: cert-manager
    release_namespace: cert-manager
    chart_ref: cert-manager/cert-manager
    chart_version: "{{ cert_manager_helm_version }}"
    create_namespace: true
    update_repo_cache: cert_manager_helm_overrides_result.changed | default(true)
    wait: true
    values_files:
      - "{{ cert_manager_helm_overrides }}"
  when: (check_helm_deployment | default(true)) or (cert_manager_helm_overrides_result.changed | default(true))

- name: cert-manager crds Yaml
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: cert-manager-crds-yml.j2
    dest: "{{ cert_manager_crds_yml }}"
    mode: 'u=rw,g=r,o=r'

- name: Deploy cert-manager crds
  become: true
  become_user: '{{ user }}'
  kubernetes.core.k8s:
    namespace: cert-manager
    state: present
    src: "{{ cert_manager_crds_yml }}"
    wait: yes
