# code: language=ansible
---
#https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/charts/opensearch-cluster/templates/opensearch-cluster-cr.yaml
#https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/charts/opensearch-operator/Chart.yaml
- name: OpenSearch Operator Helm Overrides
  become: true
  become_user: '{{ user }}'
  ansible.builtin.template:
    src: opensearch-operator-overrides-yml.j2
    dest: "{{ opensearch_operator_helm_overrides }}"
    mode: 'u=rw,g=r,o=r'
  register: opensearch_operator_helm_overrides_result

- name: Add OpenSearch Operator chart repo
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm_repository:
    name: opensearch-operator
    repo_url: "https://opensearch-project.github.io/opensearch-k8s-operator/"

- name: Deploy OpenSearch Operator helm chart
  become: true
  become_user: '{{ user }}'
  kubernetes.core.helm:
    name: opensearch-operator
    release_namespace: opensearch-operator
    chart_ref: opensearch-operator/opensearch-operator
    chart_version: "{{ opensearch_operator_helm_version }}"
    create_namespace: true
    update_repo_cache: opensearch_operator_helm_overrides_result.changed | default(true)
    wait: true
    values_files:
      - "{{ opensearch_operator_helm_overrides }}"
  when: (check_helm_deployment | default(true)) or (opensearch_operator_helm_overrides_result.changed | default(true))
